/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PaymentMethods } from "./PaymentMethods";
import { PaymentMethodsCountArgs } from "./PaymentMethodsCountArgs";
import { PaymentMethodsFindManyArgs } from "./PaymentMethodsFindManyArgs";
import { PaymentMethodsFindUniqueArgs } from "./PaymentMethodsFindUniqueArgs";
import { DeletePaymentMethodsArgs } from "./DeletePaymentMethodsArgs";
import { PaymentMethodsService } from "../paymentMethods.service";
@graphql.Resolver(() => PaymentMethods)
export class PaymentMethodsResolverBase {
  constructor(protected readonly service: PaymentMethodsService) {}

  async _paymentMethodsItemsMeta(
    @graphql.Args() args: PaymentMethodsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PaymentMethods])
  async paymentMethodsItems(
    @graphql.Args() args: PaymentMethodsFindManyArgs
  ): Promise<PaymentMethods[]> {
    return this.service.paymentMethodsItems(args);
  }

  @graphql.Query(() => PaymentMethods, { nullable: true })
  async paymentMethods(
    @graphql.Args() args: PaymentMethodsFindUniqueArgs
  ): Promise<PaymentMethods | null> {
    const result = await this.service.paymentMethods(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PaymentMethods)
  async deletePaymentMethods(
    @graphql.Args() args: DeletePaymentMethodsArgs
  ): Promise<PaymentMethods | null> {
    try {
      return await this.service.deletePaymentMethods(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
